import type { AudioItem, AudioType, ModuleDefinition } from '../types/audio';

const projectOriginalSource = {
  name: '古德眠 original beta audio',
  author: '古德眠 project',
  license: 'Project-owned original audio',
  url: 'docs/AUDIO_ASSET_SOURCES.md',
  attributionRequired: false,
};

const projectTtsSource = {
  name: '古德眠 original Mandarin TTS',
  author: '古德眠 project',
  license: 'Project-owned original script and recording',
  url: 'docs/AUDIO_ASSET_SOURCES.md',
  attributionRequired: false,
};

const soporificSource = {
  name: 'Wikimedia Commons / Free Music Archive',
  author: 'Kevin MacLeod',
  license: 'CC BY 3.0',
  url: 'https://commons.wikimedia.org/wiki/File:Kevin_MacLeod_-_Soporific.ogg',
  attributionRequired: true,
};

const ambientSource = {
  name: 'Wikimedia Commons / SoundCloud',
  author: 'Brenticus',
  license: 'CC BY 3.0',
  url: 'https://commons.wikimedia.org/wiki/File:Brenticus_-_Ambient.ogg',
  attributionRequired: true,
};

const rainSource = {
  name: 'Wikimedia Commons / PDSounds',
  author: 'ezwa',
  license: 'Public domain',
  url: 'https://commons.wikimedia.org/wiki/File:Rain_(1).ogg',
  attributionRequired: false,
};

const campfireSource = {
  name: 'Wikimedia Commons / Freesound',
  author: 'Glaneur de sons',
  license: 'CC BY 3.0',
  url: 'https://commons.wikimedia.org/wiki/File:Campfire_sound_ambience.ogg',
  attributionRequired: true,
};

const shorebirdsSource = {
  name: 'Wikimedia Commons / USFWS',
  author: 'U.S. Fish and Wildlife Service',
  license: 'Public domain',
  url: 'https://commons.wikimedia.org/wiki/File:Cape_May_Shorebirds_(distant).ogg',
  attributionRequired: false,
};

const breathingCaptions = [
  { start: 0, end: 8, text: '慢慢吸气，让肩膀松下来。' },
  { start: 8, end: 16, text: '缓缓呼气，把注意力交给声音。' },
  { start: 16, end: 24, text: '不用追赶节奏，只要安静地躺着。' },
];

const softMusicCaptions = [
  { start: 0, end: 8, text: '让第一声落下，今晚不用再用力。' },
  { start: 8, end: 16, text: '如果想到别的事，就轻轻回到音乐里。' },
  { start: 16, end: 24, text: '眼睛可以慢慢闭上，身体会自己休息。' },
];

const meditationCaptions = [
  { start: 0, end: 9, text: '感受低频声音像一条稳定的线。' },
  { start: 9, end: 18, text: '念头来了也没关系，让它慢慢经过。' },
  { start: 18, end: 28, text: '把今天放在一边，留给明天再处理。' },
];

const chimeCaptions = [
  { start: 0, end: 12, text: '每一次轻响，都是一次放松的提醒。' },
  { start: 12, end: 28, text: '不用等待下一声，只要让呼吸自然变慢。' },
  { start: 28, end: 52, text: '声音会自己远去，你也可以跟着安静下来。' },
];

const rainCaptions = [
  { start: 0, end: 9, text: '雨声落在窗边，房间变得更安静。' },
  { start: 9, end: 18, text: '听见雨滴，也听见自己的呼吸。' },
  { start: 18, end: 28, text: '让细雨陪你慢慢沉入睡意。' },
];

const oceanCaptions = [
  { start: 0, end: 10, text: '海浪远远靠近，又轻轻退回去。' },
  { start: 10, end: 20, text: '跟着起伏放松胸口和腹部。' },
  { start: 20, end: 30, text: '每一次浪声，都把紧张带走一点。' },
];

const windCaptions = [
  { start: 0, end: 10, text: '夜风很轻，只经过，不打扰。' },
  { start: 10, end: 20, text: '让身体停在柔软的位置上。' },
  { start: 20, end: 30, text: '你可以什么都不做，只是休息。' },
];

const storyCaptions = [
  { start: 0, end: 6, text: '把注意力放到声音上。' },
  { start: 6, end: 14, text: '故事会慢一点，你也可以慢一点。' },
  { start: 14, end: 24, text: '如果睡着了，就让后面的声音轻轻经过。' },
];

export const modules: ModuleDefinition[] = [
  {
    type: 'music',
    title: '听歌助眠',
    subtitle: '舒缓音乐 / 轻音乐 / 冥想音乐',
    description: '慢速旋律和低刺激音色，适合睡前放松。',
    accent: '#6D8BFF',
  },
  {
    type: 'story',
    title: '听故事助眠',
    subtitle: '故事 / 呼吸 / 身体放松',
    description: '节奏轻柔的中文故事和引导，帮助注意力慢慢安静下来。',
    accent: '#B7791F',
  },
  {
    type: 'noise',
    title: '听白噪音助眠',
    subtitle: '雨声 / 海浪 / 风声 / 粉噪',
    description: '循环环境声遮蔽干扰，适合持续陪伴入睡。',
    accent: '#1F9D86',
  },
];

export const audioCatalog: AudioItem[] = [
  {
    id: 'music-breathing-pad',
    type: 'music',
    title: 'Soporific',
    description: 'Kevin MacLeod 的舒缓环境音乐，适合长时间睡前放松。',
    duration: 290,
    category: '冥想音乐',
    asset: require('../../../assets/audio/music/soporific-kevin-macleod.ogg'),
    cover: '#6D8BFF',
    captions: breathingCaptions,
    source: soporificSource,
  },
  {
    id: 'music-moon-piano',
    type: 'music',
    title: 'Ambient',
    description: 'Brenticus 的氛围音乐，音色柔和，适合作为睡前背景。',
    duration: 265,
    category: '轻音乐',
    asset: require('../../../assets/audio/music/brenticus-ambient.ogg'),
    cover: '#8E6BFF',
    captions: softMusicCaptions,
    source: ambientSource,
  },
  {
    id: 'music-deep-meditation',
    type: 'music',
    title: '低频冥想垫底',
    description: '更低频、更稳定的环境底音，适合冥想和放空。',
    duration: 28,
    category: '舒缓音乐',
    asset: require('../../../assets/audio/music/deep-meditation.wav'),
    cover: '#4E7AC7',
    captions: meditationCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-moon-demo',
    type: 'music',
    title: '月光钢琴片段',
    description: '项目原创钢琴氛围片段，用于短时放松和播放模式体验。',
    duration: 24,
    category: '轻音乐',
    asset: require('../../../assets/audio/music/moon-piano.wav'),
    cover: '#7A8FCA',
    captions: softMusicCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-breathing-demo',
    type: 'music',
    title: '呼吸铺底片段',
    description: '项目原创呼吸引导底音，适合与睡前呼吸练习搭配。',
    duration: 24,
    category: '呼吸引导',
    asset: require('../../../assets/audio/music/breathing-pad.wav'),
    cover: '#5F9EA0',
    captions: breathingCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-soft-piano-loop',
    type: 'music',
    title: '软键入眠',
    description: '项目原创柔和键盘循环，音量起伏小，适合快速入睡。',
    duration: 50,
    category: '轻音乐',
    asset: require('../../../assets/audio/music/soft-piano-loop.wav'),
    cover: '#7184D8',
    captions: softMusicCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-warm-drone',
    type: 'music',
    title: '暖色低鸣',
    description: '项目原创暖色低频垫底，适合焦虑放松和睡前降速。',
    duration: 60,
    category: '冥想音乐',
    asset: require('../../../assets/audio/music/warm-drone.wav'),
    cover: '#5D76A9',
    captions: meditationCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-slow-chimes',
    type: 'music',
    title: '慢响风铃',
    description: '项目原创轻风铃与氛围垫底，适合把注意力从白天抽离。',
    duration: 52,
    category: '轻音乐',
    asset: require('../../../assets/audio/music/slow-chimes.wav'),
    cover: '#7A95C9',
    captions: chimeCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-night-strings',
    type: 'music',
    title: '夜色弦底',
    description: '项目原创柔和弦乐质感底音，适合故事前后的安静过渡。',
    duration: 58,
    category: '舒缓音乐',
    asset: require('../../../assets/audio/music/night-strings.wav'),
    cover: '#657CA8',
    captions: meditationCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'music-floating-pad',
    type: 'music',
    title: '漂浮垫音',
    description: '项目原创轻盈氛围垫音，适合半夜醒来后重新放松。',
    duration: 56,
    category: '冥想音乐',
    asset: require('../../../assets/audio/music/floating-pad.wav'),
    cover: '#6686B8',
    captions: breathingCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'story-stars-falling',
    type: 'story',
    title: '星星慢慢落下',
    description: '项目原创中文 TTS 睡前故事，语速较慢，适合故事助眠体验。',
    duration: 19,
    category: '温柔故事',
    asset: require('../../../assets/audio/stories/stars-falling.wav'),
    cover: '#B7791F',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-forest-letter',
    type: 'story',
    title: '森林里的晚安信',
    description: '一封来自森林小屋的晚安信，帮助注意力从白天抽离。',
    duration: 20,
    category: '自然故事',
    asset: require('../../../assets/audio/stories/forest-letter.wav'),
    cover: '#9C6A2E',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-cloud-boat',
    type: 'story',
    title: '云朵小船',
    description: '短篇云朵故事，节奏轻，适合睡前最后几分钟。',
    duration: 18,
    category: '梦境故事',
    asset: require('../../../assets/audio/stories/cloud-boat.wav'),
    cover: '#C28C3A',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-body-scan',
    type: 'story',
    title: '身体慢慢安静',
    description: '项目原创身体扫描引导，从额头到双腿逐步放松。',
    duration: 31,
    category: '身体放松',
    asset: require('../../../assets/audio/stories/body-scan.wav'),
    cover: '#A77432',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-breath-countdown',
    type: 'story',
    title: '五次呼吸倒数',
    description: '项目原创呼吸倒数引导，适合焦虑放松和睡前过渡。',
    duration: 35,
    category: '呼吸引导',
    asset: require('../../../assets/audio/stories/breath-countdown.wav'),
    cover: '#B48A42',
    captions: breathingCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-midnight-return',
    type: 'story',
    title: '半夜醒来以后',
    description: '项目原创半夜醒来安抚引导，帮助重新回到夜里的节奏。',
    duration: 28,
    category: '夜醒安抚',
    asset: require('../../../assets/audio/stories/midnight-return.wav'),
    cover: '#8F6B3A',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-lake-lantern',
    type: 'story',
    title: '湖面小灯',
    description: '项目原创短篇睡前故事，用温和画面降低思绪强度。',
    duration: 27,
    category: '梦境故事',
    asset: require('../../../assets/audio/stories/lake-lantern.wav'),
    cover: '#C99B48',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'story-garden-path',
    type: 'story',
    title: '夜里的花园小路',
    description: '项目原创睡前故事，引导注意力走进安静场景。',
    duration: 24,
    category: '温柔故事',
    asset: require('../../../assets/audio/stories/garden-path.wav'),
    cover: '#9F7A3F',
    captions: storyCaptions,
    source: projectTtsSource,
  },
  {
    id: 'noise-rain-window',
    type: 'noise',
    title: '窗边细雨',
    description: '来自 PDSounds 的真实雨声录音，默认循环播放，适合屏蔽夜间干扰。',
    duration: 45,
    category: '雨声',
    asset: require('../../../assets/audio/noise/rain-window.wav'),
    cover: '#1F9D86',
    captions: rainCaptions,
    source: rainSource,
  },
  {
    id: 'noise-ocean-waves',
    type: 'noise',
    title: '海岸远声',
    description: '美国鱼类及野生动物管理局录音，远处鸟鸣和海浪声混合。',
    duration: 14,
    category: '海岸',
    asset: require('../../../assets/audio/noise/shorebirds-waves-usfws.ogg'),
    cover: '#247BA0',
    captions: oceanCaptions,
    source: shorebirdsSource,
  },
  {
    id: 'noise-night-wind',
    type: 'noise',
    title: '篝火环境声',
    description: 'Freesound 上的真实篝火环境声，适合安静陪伴入睡。',
    duration: 60,
    category: '篝火',
    asset: require('../../../assets/audio/noise/campfire-glaneur.ogg'),
    cover: '#5C8374',
    captions: windCaptions,
    source: campfireSource,
  },
  {
    id: 'noise-rain-demo',
    type: 'noise',
    title: '细雨循环',
    description: '项目原创雨声质感循环，用于持续白噪音和定时关闭体验。',
    duration: 28,
    category: '雨声',
    asset: require('../../../assets/audio/noise/rain-window.wav'),
    cover: '#2F9E8F',
    captions: rainCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-ocean-demo',
    type: 'noise',
    title: '海浪循环',
    description: '项目原创海浪质感循环，适合列表循环和随机播放体验。',
    duration: 30,
    category: '海浪',
    asset: require('../../../assets/audio/noise/ocean-waves.wav'),
    cover: '#3B82A0',
    captions: oceanCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-brown-bed',
    type: 'noise',
    title: '棕噪睡眠底',
    description: '项目原创棕噪底音，低频稳定，适合遮盖低强度环境声。',
    duration: 55,
    category: '棕噪',
    asset: require('../../../assets/audio/noise/brown-bed.wav'),
    cover: '#456268',
    captions: windCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-pink-soft',
    type: 'noise',
    title: '柔和粉噪',
    description: '项目原创粉噪，质感比白噪更柔和，适合长时间循环。',
    duration: 55,
    category: '粉噪',
    asset: require('../../../assets/audio/noise/pink-soft.wav'),
    cover: '#6B8F8B',
    captions: windCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-forest-night',
    type: 'noise',
    title: '夜林底声',
    description: '项目原创森林夜间质感声，带轻微高频虫鸣感。',
    duration: 52,
    category: '森林',
    asset: require('../../../assets/audio/noise/forest-night.wav'),
    cover: '#3F7A5F',
    captions: windCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-creek-stones',
    type: 'noise',
    title: '石间小溪',
    description: '项目原创溪流质感声，适合自然白噪音和半夜醒来场景。',
    duration: 54,
    category: '溪流',
    asset: require('../../../assets/audio/noise/creek-stones.wav'),
    cover: '#348AA7',
    captions: oceanCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-soft-wind',
    type: 'noise',
    title: '柔风经过',
    description: '项目原创柔风底声，变化少，适合不想听旋律的夜晚。',
    duration: 50,
    category: '风声',
    asset: require('../../../assets/audio/noise/soft-wind.wav'),
    cover: '#6D8F75',
    captions: windCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-distant-thunder',
    type: 'noise',
    title: '远处闷雷',
    description: '项目原创雨夜氛围声，强度较低，适合遮盖室外杂音。',
    duration: 56,
    category: '雨夜',
    asset: require('../../../assets/audio/noise/distant-thunder.wav'),
    cover: '#52697A',
    captions: rainCaptions,
    source: projectOriginalSource,
  },
  {
    id: 'noise-room-fan',
    type: 'noise',
    title: '房间风扇',
    description: '项目原创风扇声，稳定重复，适合需要持续背景声的用户。',
    duration: 55,
    category: '风扇',
    asset: require('../../../assets/audio/noise/room-fan.wav'),
    cover: '#4D7C7A',
    captions: windCaptions,
    source: projectOriginalSource,
  },
];

export const getModule = (type: AudioType) =>
  modules.find((module) => module.type === type);

export const getItemsByType = (type: AudioType) =>
  audioCatalog.filter((item) => item.type === type);
